### ISSUE TITLE
cluster.reset is not a function

### ISSUE THREAD

**Issue by 1999** [jtblin/master-cluster#6]
```
web_1        | 
web_1        | /app/node_modules/master-cluster/reloader.js:45
web_1        |       cluster.reset();
web_1        |               ^
web_1        | TypeError: cluster.reset is not a function
web_1        |     at FSWatcher.<anonymous> (/app/node_modules/master-cluster/reloader.js:45:15)
web_1        |     at emitTwo (events.js:106:13)
web_1        |     at FSWatcher.emit (events.js:194:7)
web_1        |     at FSEvent.FSWatcher._handle.onchange (fs.js:1380:12)
```

**Comment by 1999** [comment]
This occurs when file gets changed before worker process gets forked.
